autodetect: true
max-line-length: 120

requirements:
  - requirements.txt

uses:
    - django

ignore-paths:
    - docs
    - screenshot
    - test_app
    - test_project

pylint:
    disable:
    - R0913
    
python-targets:
  - 3
